# Generated by Django 5.1.4 on 2024-12-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='company',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='company',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='Meesages',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
