# Generated by Django 5.1.4 on 2024-12-29 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_remove_company_owner_remove_permission_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('faq', models.FileField(blank=True, null=True, upload_to='faq_uploaded')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(blank=True, max_length=50, null=True)),
                ('userNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.CharField(blank=True, max_length=50, null=True)),
                ('received', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='Meesages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('msg_sender', models.CharField(blank=True, max_length=50, null=True)),
                ('msg_sender_number', models.CharField(blank=True, max_length=50, null=True)),
                ('msg_receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('msg_receiver_number', models.CharField(blank=True, max_length=50, null=True)),
                ('received', models.BooleanField(default=False)),
                ('processed_by_api', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('msgImg', models.CharField(blank=True, max_length=50, null=True)),
                ('msgFile', models.FileField(blank=True, null=True, upload_to='file_msg_uploaded')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='home.company')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_permissions', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
