# Generated by Django 5.1.4 on 2025-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
