# Generated by Django 5.1.4 on 2025-02-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_company_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meesages',
            name='msgImg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
