# Generated by Django 5.1.4 on 2025-02-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_meesages_msgimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('message_limit', models.PositiveIntegerField(help_text='تعداد پیام\u200cهای مجاز در دوره اشتراک')),
                ('company_limit', models.PositiveIntegerField(help_text='تعداد کمپانی\u200cهای مجاز')),
                ('connected_user_limit', models.PositiveIntegerField(help_text='تعداد کاربران متصل مجاز')),
                ('price', models.DecimalField(decimal_places=2, help_text='قیمت پلن به تومان', max_digits=10)),
                ('duration', models.DurationField(help_text='مدت زمان اعتبار اشتراک (مثلاً ۳۰ روز)')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('canceled', 'لغو شده'), ('failed', 'پرداخت نشده'), ('successful', 'پرداخت موفق')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, help_text='شناسه تراکنش درگاه زرین پال یا شماره سفارش', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='home.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('message_sent', models.PositiveIntegerField(default=0, help_text='تعداد پیام\u200cهای ارسال شده در دوره فعلی')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
