# Generated by Django 5.1.4 on 2025-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subscriptionplan_paymenttransaction_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='meesages',
            name='text2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'رایگان'), ('basic', 'یک ماهه'), ('premium', 'سه ماهه'), ('enterprise', 'یکساله')], max_length=50, unique=True),
        ),
    ]
