# Generated by Django 5.1.4 on 2025-04-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_meesages_text2_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meesages',
            name='text2',
        ),
    ]
