# Generated by Django 5.1.4 on 2025-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_meesages_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='meesages',
            name='question_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
