# Generated by Django 5.1.4 on 2025-05-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_meesages_question_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('embedding', models.BinaryField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_embeddings', to='home.company')),
            ],
        ),
    ]
