# Generated by Django 5.1.4 on 2025-05-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_faqembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqembedding',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faqembedding',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='faqembedding',
            name='question',
        ),
        migrations.AddField(
            model_name='faqembedding',
            name='faq',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqembedding',
            name='faq_embeddings',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faqembedding',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_data', to='home.company'),
        ),
    ]
