# Generated by Django 5.1.4 on 2025-05-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_faqembedding_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqembedding',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_embeddings', to='home.company'),
        ),
    ]
