# Generated by Django 5.1.4 on 2025-05-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_faqembedding_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='faq_embeddings',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FAQEmbedding',
        ),
    ]
