# Generated by Django 5.1.4 on 2025-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_company_faq_embeddings_delete_faqembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='faq_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
