# Generated by Django 5.1.4 on 2025-06-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_company_faq_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meesages',
            name='company',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.company'),
            preserve_default=False,
        ),
    ]
