# Generated by Django 5.1.4 on 2025-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_company_faq_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='faq_embeddings',
            new_name='faq_index_faiss',
        ),
        migrations.AddField(
            model_name='company',
            name='faq_index_metadata',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
